#!/bin/bash
#!/bin/bash
#Varwiables 
declare -a files
declare INODO
#main
declare -i parameter=0; while getopts ":n:" arg; do
  case $arg in
    n) name=$OPTARG; let parameter+=1 ;;
  esac
done 

function list_files(){
i=0
  while read line ;do
    files[$i]="$line"
    ((i++))
  done <<< "$(find / -name $name 2>/dev/null | xargs stat -c %h-%i)"  
  }


function menu(){
  for element in ${!files[@]}; do
    echo -e "${files[$element]}"
  done 
  }

if [ $parameter -ne 1 ]; then
  echo -e "Parametros ingresado incorrectos"
else
  list_files
  menu
fi

