#!/bin/bash

declare DIRECTORIES
declare nFiles
declare -i parameters=0; 
declare DIRECTORIES_ARRAY
declare Recursive
############################### COLORS
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
RESET_COLOR=$(tput sgr0)


animate() {
    local chars="/-\|"
    while :; do
      for ((i=0; i<${#chars}; i++)); do
         echo -en "${GREEN}${chars:$i:1}${RESET_COLOR}"
         sleep 0.1 
         echo -en "\b"  # Retrocede el cursor en una posicion
        done
    done
}

makeFiles ()
{
  
  echo -e "\n"
  echo -en "\t ${GREEN} [*] Creating files ${RESET_COLOR}"
  animate &
  toKill=$!

  declare cont=0;
  for element in "${DIRECTORIES_ARRAY[@]}"; do 
     for  ((i=0; i < $nFiles; i++)); do
      declare -i nRamdon=$(shuf -i 500-10000 -n 1) 
      text=$(printf "A%.s" $(seq 1 $nRamdon))
      echo $text > "$element/file-$cont.txt"
      let cont+=1
    done
  done
  kill $toKill
  echo -e "\n"

  echo -e "\n\t ${GREEN}FILES TOTAL = $cont ${RESET_COLOR} \n"
}


while getopts ":d:n:R:" arg; do
  case $arg in
    d)DIRECTORIES=$OPTARG; let parameters+=1 ;; 
    n)nFiles=$OPTARG; let parameters+=1 ;;
    R)Recursive=$OPTARG; let parameters+=1 ;;
  esac
  done

if [ $parameters -eq 2 ] && [ -n "$DIRECTORIES" ] && [ -n "$nFiles" ]; then
  IFS=" " read -ra DIRECTORIES_ARRAY <<< "$DIRECTORIES"
  makeFiles
elif [ $parameters -eq 2 ] && [ -n "$Recursive" ] && [ -n "$nFiles" ]; then
  mapfile -t DIRECTORIES_ARRAY < <(find $Recursive -type d)
  makeFiles
else
  echo -e "INVALID PARAMETER"
fi
